### ISSUE TITLE
NullPointerException in javax.swing.text.FlowView$FlowStrategy.createView(FlowView.java:679)

### ISSUE THREAD

**Issue by foolo** [foolo/tnt#1]
Steps to reproduce:

Select a word by doubleclicking in target column. Replace it by typing a letter. Repeat the same operation (doubleclick+type) a few times (usually 3-5).

Result:

```
2020-08-05T16:21:51.603+02:00 : SEVERE : null
java.lang.NullPointerException
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.createView(FlowView.java:679)
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:533)
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:489)
	at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:209)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1821)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:948)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1345)
	at Tnt/tnt.editor.SegmentView.updateHeight(SegmentView.java:339)
	at Tnt/tnt.editor.SegmentView.markupViewTargetCaretUpdate(SegmentView.java:521)
	at Tnt/tnt.editor.SegmentView$4.caretUpdate(SegmentView.java:408)
	at java.desktop/javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:412)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4489)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4511)
	at java.desktop/javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:812)
	at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1283)
	at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1182)
	at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1163)
	at java.desktop/javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1757)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument$DefaultFilterBypass.replace(AbstractDocument.java:3217)
	at java.desktop/javax.swing.text.DocumentFilter.replace(DocumentFilter.java:120)
	at Tnt/tnt.editor.EditableMarkupView$MyDocumentFilter.replace(EditableMarkupView.java:78)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at java.desktop/javax.swing.JTextPane.replaceSelection(JTextPane.java:190)
	at java.desktop/javax.swing.JTextPane.replaceSelection(JTextPane.java:173)
	at java.desktop/javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

See mininal example on branch "bug1"

**Comment by foolo** [comment]
Bug disappears when removing MarkupView.updateUI() override, and when removing inputAttributes.removeAttributes(inputAttributes); from SpellCheck.clearStyle

**Comment by foolo** [comment]
MarkupView.updateUI() was added in commit 8d66d5e34976fe65bebcc979ff580234546779ab
See https://stackoverflow.com/questions/58690711/jtextarea-selection-behavior-on-double-triple-click-moving-mouse
SpellCheck was added in 26e4a8831609335e37076d3abac047a98b6dc630

**Comment by foolo** [comment]
Seems to be possible to solve by removing "inputAttributes.removeAttributes(inputAttributes);" from SpellCheck.clearStyle
Needs long term testing
